### ISSUE TITLE
Update Arch Linux data source to reproducible.archlinux.org

### ISSUE THREAD

**Issue by kpcyrd** [bmwiedemann/ismypackagereproducibleyet#5]
While checking the status of [kitty](https://ismypackagereproducibleyet.org/?pkg=kitty&query=query) I noticed it's listed as "fails to build from source" on Arch Linux because the status is pulled from `tests.reproducible-builds.org`. There's some known issues with this one and it's generally recommended to use `reproducible.archlinux.org`, since this data is for rebuild attempts of the actual binary packages distributed to users.

Json data can be fetched from here:

```
https://reproducible.archlinux.org/api/v0/pkgs/list
```

Thanks!

**Comment by bmwiedemann** [comment]
Your format is slightly different from https://rb.zq1.de/spec/json-format.txt
```json
[
  {
    "name": "0ad",
    "version": "a26-14",
    "status": "GOOD",
    "distro": "archlinux",
    "suite": "extra",
    "architecture": "x86_64",
    "artifact_url": "https://geo.mirror.pkgbuild.com/extra/os/x86_64/0ad-a26-14-x86_64.pkg.tar.zst",
    "build_id": 626841,
    "built_at": "2024-05-22T23:04:25.781533388",
    "has_diffoscope": false,
    "has_attestation": true
  },
 ...
]
```

Would you do conversion on your side?

I think, I mostly need `package` instead of `name` and a `status` with different values.

**Comment by bmwiedemann** [comment]
I added some client-side mapping in #6 if server-side transformation is too hard. Still needs some review+love.
